pool:
  vmImage: windows-latest

steps:
- powershell: .\Build\build.ps1
  displayName: Start The Build

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**/TEST-*.xml'
    mergeTestResults: true
    failTaskOnFailedTests: true
    testRunTitle: 'Test Run'


